### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by keshi02** [keshi02/tragicomic#9]
issueを作成しました。
ご確認よろしくお願いいたします。

### 概要

- issueの作成と提出
- ストーリーポイントの設定

### 実装予定の機能（MVP時点）

- [ ] 会員登録
- [ ] ログイン機能
- [ ] やらかし投稿一覧機能
- [ ] やらかし投稿機能
- [ ] やらかし投稿編集機能
- [ ] やらかし投稿削除機能
- [ ] リアクション機能

### 必要なページ

- [ ] 会員登録
- [ ] ログイン
- [ ] パスワード再設定用メールアドレス入力
- [ ] パスワード再設定
- [ ] やらかし投稿一覧
- [ ] やらかし投稿作成
- [ ] やらかし投稿編集
- [ ] トップページ

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。

GitHubProjectsのリンクもご共有いただいてよろしいでしょうか？（`public`の設定もお願いします）

**Comment by keshi02** [comment]
コメントありがとうございます。
ProjectのURLになります
https://github.com/users/keshi02/projects/2

**Comment by tarakish** [comment]
ご回答ありがとうございます。
こちらのリポジトリのProjectsに紐づけるようにしていただけますか？
![スクリーンショット 2024-03-16 10 28 23](https://github.com/keshi02/tragicomic/assets/71510236/9990b9d9-123d-49db-b2e5-b96f52e9fb48)

**Comment by keshi02** [comment]
ありがとうございます🙇
ご確認よろしくお願いいたします。
> こちらのリポジトリのProjectsに紐づけるようにしていただけますか？


[![Image from Gyazo](https://i.gyazo.com/01600266c0943a06309ae727fc12e0bf.png)](https://gyazo.com/01600266c0943a06309ae727fc12e0bf)

**Comment by tarakish** [comment]
確認できました。LGTMです！
ストーリーポイントが5のものは開発しながらで良いので、2や3など細分化できると良さそうです👍
